In [2]:
import numpy as np

In [ ]:
# scaler, 0D tensor
a = np.array(1) 
# vector, 1D tensor
b = np.array([2,3]) 
# matrix, 2D tensor 
c = np.array([[4,5], [6,7]]) 
# 3D tensor
d = np.array([[[4,5,0,0], [6,7,0,0]], [[4,5,0,0], [6,7,0,0]], [[4,5,0,0], [6,7,0,0]]]) 

ndim: number of dimentions

shape: tuple of number of elements in each dimentions

size: total number of elements

dtype: data type

In [ ]:
def show_properties(arr):
    print(f'array: \n{arr}')
    print(f'number of dimentions: {arr.ndim}')
    # .shape returns tuple as output
    print(f'shape: {arr.shape}') 
    print(f'size {arr.size}')
    print(f'data type: {arr.dtype}')
    print("\n\n")

show_properties(a)
show_properties(b)
show_properties(c)
show_properties(d)

# Numpy functions for creating tensors

In [ ]:
# .zeros(), .ones() and .random.random() takes shape tuple as input
# .eye() takes shape of one dimention as input and creates a 2D tensor 

print ("np.zeros((2,2)):\n", np.zeros((3,2,4)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2))) # identity matrix
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

# Indexing
- Similar to python lists
- index start at 0
- negative index allowed

In [ ]:
arr = np.array([[[4,5,8,9], [6,7,1,2]], [[4,5,3,9], [6,7,2,6]], [[4,5,1,9], [6,7,4,7]]]) 

print("arr", arr, "\n")
print("arr[2,0,1]\n", arr[2,0,1], "\n")
print("arr[1:2, 0:2, 1:3]\n", arr[1:2, 0:2, 1:3], "\n")

## Slicing

In [ ]:
print(arr, "\n")
print ("arr[1,:,2]\n", arr[1,:,2])

## Integer array Indexing

In [ ]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

rows = np.array([0, 1, 2])
print ("rows_to_get: ", rows)

cols = np.array([0, 2, 1])
print ("cols_to_get: ", cols)

# Combine sequences above to get values to get
print ("indexed values: ", x[rows, cols]) 
# (0, 0), (1, 2), (2, 1)

## Boolean array indexing

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])

# Math

## Arithmatic

In [ ]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

## Dot product

In [8]:
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
# or 
d = np.dot(a, b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print(d.shape, "\n")
print (c, "\n")
print (d, "\n")

(2, 3) · (3, 2) = (2, 2)
(2, 2) 

[[ 58.  64.]
 [139. 154.]] 

[[ 58.  64.]
 [139. 154.]] 



## Axis operations

In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

### Min / max

In [ ]:
x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

# Broadcast 

In [ ]:
x = np.array([[1,2], [3,2]]) # vector
y = np.array(3) # scalar
z = x + y
print ("z:\n", z)

**Uninted broadcasting**

In [ ]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
c = a + b
print(a, "\n")
print(b, "\n")
print(c)

We need to be careful to ensure that a is the same shape as b if we don't want this unintentional broadcasting behavior.

 np.expand_dims is used to expand the shape of an array by adding an additional axis.

# Expanding dimentions

In [ ]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=0)
c = np.expand_dims(b, axis=0)
d = np.expand_dims(b, axis=2)

print(a, "\n")
print(b, "\n")
print(c, "\n")
print(d, "\n")

print(a.ndim, b.ndim, c.ndim, d.ndim, "\n")
print(a.shape, b.shape, c.shape, d.shape)

# Transpose
### Default Transposition (Reverse Dimensions):
When using arr.T it just reverses the dimentions,

for example, if dimention is (2,3,4) after transpose it becomes (4,3,2)

shape before transpose: (2,3,4)

shape after transpose: (4,3,2)

### Transpose using Specified Axes:

In the previous example if we specify the dimention like (1,0,2) that the first axis becomes the second, the second axis becomes the first, and the third axis remains unchanged.

shape before transpose: (2,3,4)

shape after transpose: (3,2,4)


In [24]:
x = np.array([[1,2,3], [4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print ("y:\n", y)
print ("y.shape: ", y.shape)

# or
z = x.T
print ("z:\n", z)
print ("z.shape: ", z.shape)

a = np.array([[[4,5,8,9], [6,7,1,2]], [[4,5,3,9], [6,7,2,6]], [[4,5,1,9], [6,7,4,7]]]) 
print ("a:\n", a)
print ("a.shape: ", a.shape)

b = a.T
print ("b:\n", b)
print ("b.shape: ", b.shape)


c = np.transpose(a, (1,0,2))
print ("c:\n", c)
print ("c.shape: ", c.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[1 4]
 [2 5]
 [3 6]]
y.shape:  (3, 2)
z:
 [[1 4]
 [2 5]
 [3 6]]
z.shape:  (3, 2)
a:
 [[[4 5 8 9]
  [6 7 1 2]]

 [[4 5 3 9]
  [6 7 2 6]]

 [[4 5 1 9]
  [6 7 4 7]]]
a.shape:  (3, 2, 4)
a:
 [[[4 4 4]
  [6 6 6]]

 [[5 5 5]
  [7 7 7]]

 [[8 3 1]
  [1 2 4]]

 [[9 9 9]
  [2 6 7]]]
a.shape:  (4, 2, 3)


# Reshape
np.reshape() takes the original array and desired shape tuple as input.

We can pass one unknown shape to the shape tuple as (-1) and the method will infer the shape based on shapes of other dimentions. We can only pass one unknown dimention.

In [21]:
x = np.array([[1,2,3,4,5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y: \n", y)
print ("y.shape: ", y.shape)
z = np.reshape(x, (2, -1))
print ("z: \n", z)
print ("z.shape: ", z.shape)

x = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
a = np.reshape(x, (3,2, -1))
print ("a: \n", a)
print ("a.shape: ", a.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)
a: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
a.shape:  (3, 2, 2)


### Unintended Reshape

In [4]:
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
            [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.shape:  (2, 3, 4)


**want to reshape like**

[[ 1  1  1  1 10 10 10 10]

[ 2  2  2  2 20 20 20 20]

[ 3  3  3  3 30 30 30 30]]

but if reshape normally we get,

[[ 1  1  1  1  2  2  2  2]

[ 3  3  3  3 10 10 10 10]

[20 20 20 20 30 30 30 30]]

In [28]:
y = np.reshape(x, (3,8))
print ("y:\n", y)
print ("y.shape: ", y.shape)

y:
 [[ 1  1  1  1  2  2  2  2]
 [ 3  3  3  3 10 10 10 10]
 [20 20 20 20 30 30 30 30]]
y.shape:  (3, 8)


### correct way of reshaping previous array

If we transpose the tensor and then do a reshape, we get our desired tensor. Transpose allows us to put our two vectors that we want to combine together and then we use reshape to join them together.

**As a general rule, we should always get our dimensions together before reshaping to combine them.**

In [5]:
z = np.transpose(x, (1,0,2))
a = np.reshape(z, (3,8))

print ("z:\n", z)
print ("z.shape: ", z.shape)

print ("a:\n", a)
print ("a.shape: ", a.shape)

z:
 [[[ 1  1  1  1]
  [10 10 10 10]]

 [[ 2  2  2  2]
  [20 20 20 20]]

 [[ 3  3  3  3]
  [30 30 30 30]]]
z.shape:  (3, 2, 4)
a:
 [[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]
a.shape:  (3, 8)


# Joining

In [30]:
x = np.array(
    [
        [4, 5, 8, 9],
        [4, 5, 3, 9],
        [4, 5, 1, 9],
    ]
)
print (x)
print (x.shape)

[[4 5 8 9]
 [4 5 3 9]
 [4 5 1 9]]
(3, 4)


In [11]:
# Concatenation
y = np.concatenate([x, x], axis=0)  # concat on a specified axis
print(y)
print(y.shape)


[[0.08275736 0.55136171 0.49452921]
 [0.80023976 0.39510782 0.03265257]
 [0.08275736 0.55136171 0.49452921]
 [0.80023976 0.39510782 0.03265257]]
(4, 3)


In [33]:
# Stacking
z = np.stack([x, x], axis=1)  # stack on new axis
print(x)
print(z)
print(z.shape)

[[4 5 8 9]
 [4 5 3 9]
 [4 5 1 9]]
[[[4 5 8 9]
  [4 5 8 9]]

 [[4 5 3 9]
  [4 5 3 9]]

 [[4 5 1 9]
  [4 5 1 9]]]
(3, 2, 4)


# Expanding and Reducing Dimentions

This can also be done by using reshape()

In [34]:
# Adding dimensions
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n", x)
print("x.shape: ", x.shape)
y = np.expand_dims(x, 1)  # expand dim 1
print("y: \n", y)
print("y.shape: ", y.shape)  # notice extra set of brackets are added

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


In [37]:
# Removing dimensions
x = np.array([[[1, 2, 3]], [[4, 5, 6]]])
print("x:\n", x)
print("x.shape: ", x.shape)
y = np.squeeze(x, 1)  # squeeze dim 1
print("y: \n", y)
print("y.shape: ", y.shape)  # notice extra set of brackets are gone


x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
